#!/usr/bin/env bash
# Copyright  observIQ, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

touch tls/index.txt
echo 00 > tls/serial

cat <<- EOF > tls/openssl.conf
[ ca ]
default_ca      = my_ca
[ my_ca ]
database        = tls/index.txt
serial          = tls/serial
new_certs_dir   = tls/
x509_extensions = my_cert
name_opt         = ca_default
cert_opt         = ca_default
default_md       = default
policy           = policy_match
# 'copy_extensions' will copy over SAN ("X509v3 Subject Alternative Name") from CSR
copy_extensions = copy

[ my_cert ]
basicConstraints        = CA:FALSE
nsComment               = "generated by github.com/observiq/bindplane"
subjectKeyIdentifier    = hash
authorityKeyIdentifier  = keyid,issuer

[ policy_match ]
# ensure CSR fields match that of delivered Cert
countryName             = match
stateOrProvinceName     = match
organizationName        = match
organizationalUnitName  = optional
commonName              = supplied
emailAddress            = optional

EOF

irs_pki() {
    # certificate authority
    openssl genrsa -out tls/bindplane-ca.key 4096
    openssl req -new -x509 -sha256 \
        -key tls/bindplane-ca.key \
        -out tls/bindplane-ca.crt \
        -days 10950 \
        -subj "/C=US/ST=Michigan/L=GrandRapids/O=observIQ/OU=bindplane/CN=bindplane-ca"

    # certificate
    openssl genrsa -out tls/bindplane.key 4096
    openssl req -new -key tls/bindplane.key -out tls/bindplane.csr \
        -subj "/C=US/ST=Michigan/L=GrandRapids/O=observIQ/OU=bindplane/CN=localhost" \
        -addext "subjectAltName=DNS:localhost,DNS:bindplane.bindplane-dev.svc.cluster.local"
    openssl ca \
        -create_serial \
        -cert tls/bindplane-ca.crt \
        -keyfile tls/bindplane-ca.key \
        -days 9125 \
        -in tls/bindplane.csr \
        -batch \
        -config tls/openssl.conf \
        -out tls/bindplane.crt

    # append ca.crt to server certificate
    cat tls/bindplane-ca.crt >> tls/bindplane.crt    

    # client cert
    openssl genrsa -out tls/bindplane-client.key 4096
    openssl req -new -key tls/bindplane-client.key -out tls/bindplane-client.csr \
        -subj "/C=US/ST=Michigan/L=GrandRapids/O=observIQ/OU=bindplane/CN=bindplane-dev-client"
    openssl ca \
        -create_serial \
        -cert tls/bindplane-ca.crt \
        -keyfile tls/bindplane-ca.key \
        -days 9125 \
        -in tls/bindplane-client.csr \
        -batch \
        -config tls/openssl.conf \
        -out tls/bindplane-client.crt
}

test_pki() {
    # certificate authority
    openssl genrsa -out tls/test-ca.key 4096
    openssl req -new -x509 -sha256 \
        -key tls/test-ca.key \
        -out tls/test-ca.crt \
        -days 10950 \
        -subj "/C=US/ST=Michigan/L=GrandRapids/O=observIQ/OU=test/CN=test-ca"

    # certificate
    openssl genrsa -out tls/test.key 4096
    openssl req -new -key tls/test.key -out tls/test.csr \
        -subj "/C=US/ST=Michigan/L=GrandRapids/O=observIQ/OU=test/CN=localhost" \
        -addext "subjectAltName=DNS:localhost,DNS:bindplane.bindplane-dev.svc.cluster.local"
    openssl ca \
        -create_serial \
        -cert tls/test-ca.crt \
        -keyfile tls/test-ca.key \
        -days 9125 \
        -in tls/test.csr \
        -batch \
        -config tls/openssl.conf \
        -out tls/test.crt

    # append ca.crt to server certificate
    cat tls/test-ca.crt >> tls/test.crt    

    # client cert
    openssl genrsa -out tls/test-client.key 4096
    openssl req -new -key tls/test-client.key -out tls/test-client.csr \
        -subj "/C=US/ST=Michigan/L=GrandRapids/O=observIQ/OU=test/CN=test-dev-client"
    openssl ca \
        -create_serial \
        -cert tls/test-ca.crt \
        -keyfile tls/test-ca.key \
        -days 9125 \
        -in tls/test-client.csr \
        -batch \
        -config tls/openssl.conf \
        -out tls/test-client.crt
}

permissions() {
    chmod 0644 tls/*
}

irs_pki
test_pki
permissions
